module Api
  class UptimeController < ApplicationController
    include ActionController::MimeResponds
    respond_to :json

    def uptime_json
      render json: {
        avg_downtime_pct: 0.0,
        chart_data: [
          { label: "13 May UTC", color: "green", class: "up" },
          { label: "12 May UTC", color: "green", class: "up" },
          { label: "11 May UTC", color: "green", class: "up" },
          { label: "10 May UTC", color: "green", class: "up" },
          { label: "09 May UTC", color: "green", class: "up" },
          { label: "08 May UTC", color: "green", class: "up" },
          { label: "07 May UTC", color: "green", class: "up" },
          { label: "06 May UTC", color: "green", class: "up" },
          { label: "05 May UTC", color: "green", class: "up" },
          { label: "04 May UTC", color: "green", class: "up" },
          { label: "03 May UTC", color: "green", class: "up" },
          { label: "02 May UTC", color: "green", class: "up" },
          { label: "01 May UTC", color: "green", class: "up" },
          { label: "30 Apr UTC", color: "green", class: "up" },
          { label: "29 Apr UTC", color: "green", class: "up" },
          { label: "28 Apr UTC", color: "green", class: "up" },
          { label: "27 Apr UTC", color: "green", class: "up" },
          { label: "26 Apr UTC", color: "green", class: "up" },
          { label: "25 Apr UTC", color: "green", class: "up" },
          { label: "24 Apr UTC", color: "green", class: "up" },
          { label: "23 Apr UTC", color: "green", class: "up" },
          { label: "22 Apr UTC", color: "green", class: "up" },
          { label: "21 Apr UTC", color: "green", class: "up" },
          { label: "20 Apr UTC", color: "green", class: "up" },
          { label: "19 Apr UTC", color: "green", class: "up" },
          { label: "18 Apr UTC", color: "green", class: "up" },
          { label: "17 Apr UTC", color: "green", class: "up" },
          { label: "16 Apr UTC", color: "green", class: "up" },
          { label: "15 Apr UTC", color: "green", class: "up" },
          { label: "14 Apr UTC", color: "green", class: "up" },
          { label: "13 Apr UTC", color: "green", class: "up" },
          { label: "12 Apr UTC", color: "green", class: "up" },
          { label: "11 Apr UTC", color: "green", class: "up" },
          { label: "10 Apr UTC", color: "green", class: "up" },
          { label: "09 Apr UTC", color: "green", class: "up" },
          { label: "08 Apr UTC", color: "green", class: "up" },
          { label: "07 Apr UTC", color: "green", class: "up" },
          { label: "06 Apr UTC", color: "green", class: "up" },
          { label: "05 Apr UTC", color: "green", class: "up" },
          { label: "04 Apr UTC", color: "green", class: "up" },
          { label: "03 Apr UTC", color: "green", class: "up" },
          { label: "02 Apr UTC", color: "green", class: "up" },
          { label: "01 Apr UTC", color: "green", class: "up" },
          { label: "31 Mar UTC", color: "green", class: "up" },
          { label: "30 Mar UTC", color: "green", class: "up" },
          { label: "29 Mar UTC", color: "green", class: "up" },
          { label: "28 Mar UTC", color: "green", class: "up" },
          { label: "27 Mar UTC", color: "green", class: "up" },
          { label: "26 Mar UTC", color: "green", class: "up" },
          { label: "25 Mar UTC", color: "green", class: "up" },
          { label: "24 Mar UTC", color: "green", class: "up" },
          { label: "23 Mar UTC", color: "green", class: "up" },
          { label: "22 Mar UTC", color: "green", class: "up" },
          { label: "21 Mar UTC", color: "green", class: "up" },
          { label: "20 Mar UTC", color: "green", class: "up" },
          { label: "19 Mar UTC", color: "green", class: "up" },
          { label: "18 Mar UTC", color: "green", class: "up" },
          { label: "17 Mar UTC", color: "green", class: "up" },
          { label: "16 Mar UTC", color: "green", class: "up" },
          { label: "15 Mar UTC", color: "green", class: "up" },
          { label: "14 Mar UTC", color: "green", class: "up" },
          { label: "13 Mar UTC", color: "green", class: "up" },
          { label: "12 Mar UTC", color: "green", class: "up" },
          { label: "11 Mar UTC", color: "green", class: "up" },
          { label: "10 Mar UTC", color: "green", class: "up" },
          { label: "09 Mar UTC", color: "green", class: "up" },
          { label: "08 Mar UTC", color: "green", class: "up" },
          { label: "07 Mar UTC", color: "green", class: "up" },
          { label: "06 Mar UTC", color: "green", class: "up" },
          { label: "05 Mar UTC", color: "green", class: "up" },
          { label: "04 Mar UTC", color: "green", class: "up" },
          { label: "03 Mar UTC", color: "green", class: "up" },
          { label: "02 Mar UTC", color: "green", class: "up" },
          { label: "01 Mar UTC", color: "green", class: "up" },
          { label: "28 Feb UTC", color: "green", class: "up" },
          { label: "27 Feb UTC", color: "green", class: "up" },
          { label: "26 Feb UTC", color: "green", class: "up" },
          { label: "25 Feb UTC", color: "green", class: "up" },
          { label: "24 Feb UTC", color: "green", class: "up" },
          { label: "23 Feb UTC", color: "green", class: "up" },
          { label: "22 Feb UTC", color: "green", class: "up" },
          { label: "21 Feb UTC", color: "green", class: "up" },
          { label: "20 Feb UTC", color: "green", class: "up" },
          { label: "19 Feb UTC", color: "green", class: "up" },
          { label: "18 Feb UTC", color: "green", class: "up" },
          { label: "17 Feb UTC", color: "green", class: "up" },
          { label: "16 Feb UTC", color: "green", class: "up" },
          { label: "15 Feb UTC", color: "green", class: "up" },
          { label: "14 Feb UTC", color: "green", class: "up" },
          { label: "13 Feb UTC", color: "green", class: "up" },
        ],
        chart_legend: [
          {
            up: "All good",
            trouble: "Performance issue",
            down: "Service disruption",
          },
        ],
      }
    end
  end
end
