module.exports = [
  {
    name: "Core",
    directory: "core",
    components: [
      "FeaturedLink",
      "SignOutLink",
      "Meganav",
      "Loader",
      "Logo",
      "MeganavContentProducts",
      "MeganavContentCompany",
      "MeganavContentDevelopers",
      "MeganavContentUseCases",
      "MeganavControlMobilePanelClose",
      "MeganavControlMobilePanelOpen",
      "MeganavControl",
      "MeganavControlMobileDropdown",
      "MeganavItemsDesktop",
      "MeganavItemsSignedIn",
      "MeganavItemsMobile",
      "MeganavBlogPostsList",
      "Notice",
      "ContactFooter",
      "FeatureFooter",
      "Footer",
      "Code",
      "ConnectStateWrapper",
      "Flash",
      "CookieMessage",
      "Icon",
      "Slider",
      "CustomerLogos",
      "CompanyAutocomplete",
      "MeganavSearch",
      "MeganavSearchSuggestions",
      "MeganavSearchPanel",
      "MeganavSearchAutocomplete",
      "DropdownMenu",
    ],
  },
  {
    name: "Reset",
    directory: "reset",
    components: [],
  },
];
