# Temporary stub to allow CircleCi to pass until it is able to be disabled for ably-ui

workflows:
  version: 2
  build:
    jobs:
      - cypress_tests
      - lint
      - format_check

jobs: # do nothing
  lint:
    docker:
      - image: cimg/base:2022.06-22.04
    resource_class: small
    run: echo noop
  cypress_tests:
    docker:
      - image: cimg/base:2022.06-22.04
    resource_class: small
    run: echo noop
  format_check:
    docker:
      - image: cimg/base:2022.06-22.04
    resource_class: small
    run: echo noop
