import { ColorClass, Theme } from "./types";

const textColorMappings: { dark: ColorClass; light: ColorClass }[] = [
  { dark: "text-neutral-000", light: "text-neutral-1300" },
  { dark: "text-neutral-100", light: "text-neutral-1200" },
  { dark: "text-neutral-200", light: "text-neutral-1100" },
  { dark: "text-neutral-300", light: "text-neutral-1000" },
  { dark: "text-neutral-400", light: "text-neutral-900" },
  { dark: "text-neutral-500", light: "text-neutral-800" },
  { dark: "text-neutral-600", light: "text-neutral-700" },
  { dark: "text-neutral-700", light: "text-neutral-600" },
  { dark: "text-neutral-800", light: "text-neutral-500" },
  { dark: "text-neutral-900", light: "text-neutral-400" },
  { dark: "text-neutral-1000", light: "text-neutral-300" },
  { dark: "text-neutral-1100", light: "text-neutral-200" },
  { dark: "text-neutral-1200", light: "text-neutral-100" },
  { dark: "text-neutral-1300", light: "text-neutral-000" },
  { dark: "text-orange-100", light: "text-orange-1100" },
  { dark: "text-orange-200", light: "text-orange-1000" },
  { dark: "text-orange-300", light: "text-orange-900" },
  { dark: "text-orange-400", light: "text-orange-800" },
  { dark: "text-orange-500", light: "text-orange-700" },
  { dark: "text-orange-600", light: "text-orange-600" },
  { dark: "text-orange-700", light: "text-orange-500" },
  { dark: "text-orange-800", light: "text-orange-400" },
  { dark: "text-orange-900", light: "text-orange-300" },
  { dark: "text-orange-1000", light: "text-orange-200" },
  { dark: "text-orange-1100", light: "text-orange-100" },
  { dark: "text-yellow-100", light: "text-yellow-900" },
  { dark: "text-yellow-200", light: "text-yellow-800" },
  { dark: "text-yellow-300", light: "text-yellow-700" },
  { dark: "text-yellow-400", light: "text-yellow-600" },
  { dark: "text-yellow-500", light: "text-yellow-500" },
  { dark: "text-yellow-600", light: "text-yellow-400" },
  { dark: "text-yellow-700", light: "text-yellow-300" },
  { dark: "text-yellow-800", light: "text-yellow-200" },
  { dark: "text-yellow-900", light: "text-yellow-100" },
  { dark: "text-green-100", light: "text-green-900" },
  { dark: "text-green-200", light: "text-green-800" },
  { dark: "text-green-300", light: "text-green-700" },
  { dark: "text-green-400", light: "text-green-600" },
  { dark: "text-green-500", light: "text-green-500" },
  { dark: "text-green-600", light: "text-green-400" },
  { dark: "text-green-700", light: "text-green-300" },
  { dark: "text-green-800", light: "text-green-200" },
  { dark: "text-green-900", light: "text-green-100" },
  { dark: "text-blue-100", light: "text-blue-900" },
  { dark: "text-blue-200", light: "text-blue-800" },
  { dark: "text-blue-300", light: "text-blue-700" },
  { dark: "text-blue-400", light: "text-blue-600" },
  { dark: "text-blue-500", light: "text-blue-500" },
  { dark: "text-blue-600", light: "text-blue-400" },
  { dark: "text-blue-700", light: "text-blue-300" },
  { dark: "text-blue-800", light: "text-blue-200" },
  { dark: "text-blue-900", light: "text-blue-100" },
  { dark: "text-violet-100", light: "text-violet-900" },
  { dark: "text-violet-200", light: "text-violet-800" },
  { dark: "text-violet-300", light: "text-violet-700" },
  { dark: "text-violet-400", light: "text-violet-600" },
  { dark: "text-violet-500", light: "text-violet-500" },
  { dark: "text-violet-600", light: "text-violet-400" },
  { dark: "text-violet-700", light: "text-violet-300" },
  { dark: "text-violet-800", light: "text-violet-200" },
  { dark: "text-violet-900", light: "text-violet-100" },
  { dark: "text-pink-100", light: "text-pink-900" },
  { dark: "text-pink-200", light: "text-pink-800" },
  { dark: "text-pink-300", light: "text-pink-700" },
  { dark: "text-pink-400", light: "text-pink-600" },
  { dark: "text-pink-500", light: "text-pink-500" },
  { dark: "text-pink-600", light: "text-pink-400" },
  { dark: "text-pink-700", light: "text-pink-300" },
  { dark: "text-pink-800", light: "text-pink-200" },
  { dark: "text-pink-900", light: "text-pink-100" },
  { dark: "hover:text-neutral-000", light: "hover:text-neutral-1300" },
  { dark: "hover:text-neutral-100", light: "hover:text-neutral-1200" },
  { dark: "hover:text-neutral-200", light: "hover:text-neutral-1100" },
  { dark: "hover:text-neutral-300", light: "hover:text-neutral-1000" },
  { dark: "hover:text-neutral-400", light: "hover:text-neutral-900" },
  { dark: "hover:text-neutral-500", light: "hover:text-neutral-800" },
  { dark: "hover:text-neutral-600", light: "hover:text-neutral-700" },
  { dark: "hover:text-neutral-700", light: "hover:text-neutral-600" },
  { dark: "hover:text-neutral-800", light: "hover:text-neutral-500" },
  { dark: "hover:text-neutral-900", light: "hover:text-neutral-400" },
  { dark: "hover:text-neutral-1000", light: "hover:text-neutral-300" },
  { dark: "hover:text-neutral-1100", light: "hover:text-neutral-200" },
  { dark: "hover:text-neutral-1200", light: "hover:text-neutral-100" },
  { dark: "hover:text-neutral-1300", light: "hover:text-neutral-000" },
  { dark: "hover:text-orange-100", light: "hover:text-orange-1100" },
  { dark: "hover:text-orange-200", light: "hover:text-orange-1000" },
  { dark: "hover:text-orange-300", light: "hover:text-orange-900" },
  { dark: "hover:text-orange-400", light: "hover:text-orange-800" },
  { dark: "hover:text-orange-500", light: "hover:text-orange-700" },
  { dark: "hover:text-orange-600", light: "hover:text-orange-600" },
  { dark: "hover:text-orange-700", light: "hover:text-orange-500" },
  { dark: "hover:text-orange-800", light: "hover:text-orange-400" },
  { dark: "hover:text-orange-900", light: "hover:text-orange-300" },
  { dark: "hover:text-orange-1000", light: "hover:text-orange-200" },
  { dark: "hover:text-orange-1100", light: "hover:text-orange-100" },
  { dark: "hover:text-yellow-100", light: "hover:text-yellow-900" },
  { dark: "hover:text-yellow-200", light: "hover:text-yellow-800" },
  { dark: "hover:text-yellow-300", light: "hover:text-yellow-700" },
  { dark: "hover:text-yellow-400", light: "hover:text-yellow-600" },
  { dark: "hover:text-yellow-500", light: "hover:text-yellow-500" },
  { dark: "hover:text-yellow-600", light: "hover:text-yellow-400" },
  { dark: "hover:text-yellow-700", light: "hover:text-yellow-300" },
  { dark: "hover:text-yellow-800", light: "hover:text-yellow-200" },
  { dark: "hover:text-yellow-900", light: "hover:text-yellow-100" },
  { dark: "hover:text-green-100", light: "hover:text-green-900" },
  { dark: "hover:text-green-200", light: "hover:text-green-800" },
  { dark: "hover:text-green-300", light: "hover:text-green-700" },
  { dark: "hover:text-green-400", light: "hover:text-green-600" },
  { dark: "hover:text-green-500", light: "hover:text-green-500" },
  { dark: "hover:text-green-600", light: "hover:text-green-400" },
  { dark: "hover:text-green-700", light: "hover:text-green-300" },
  { dark: "hover:text-green-800", light: "hover:text-green-200" },
  { dark: "hover:text-green-900", light: "hover:text-green-100" },
  { dark: "hover:text-blue-100", light: "hover:text-blue-900" },
  { dark: "hover:text-blue-200", light: "hover:text-blue-800" },
  { dark: "hover:text-blue-300", light: "hover:text-blue-700" },
  { dark: "hover:text-blue-400", light: "hover:text-blue-600" },
  { dark: "hover:text-blue-500", light: "hover:text-blue-500" },
  { dark: "hover:text-blue-600", light: "hover:text-blue-400" },
  { dark: "hover:text-blue-700", light: "hover:text-blue-300" },
  { dark: "hover:text-blue-800", light: "hover:text-blue-200" },
  { dark: "hover:text-blue-900", light: "hover:text-blue-100" },
  { dark: "hover:text-violet-100", light: "hover:text-violet-900" },
  { dark: "hover:text-violet-200", light: "hover:text-violet-800" },
  { dark: "hover:text-violet-300", light: "hover:text-violet-700" },
  { dark: "hover:text-violet-400", light: "hover:text-violet-600" },
  { dark: "hover:text-violet-500", light: "hover:text-violet-500" },
  { dark: "hover:text-violet-600", light: "hover:text-violet-400" },
  { dark: "hover:text-violet-700", light: "hover:text-violet-300" },
  { dark: "hover:text-violet-800", light: "hover:text-violet-200" },
  { dark: "hover:text-violet-900", light: "hover:text-violet-100" },
  { dark: "hover:text-pink-100", light: "hover:text-pink-900" },
  { dark: "hover:text-pink-200", light: "hover:text-pink-800" },
  { dark: "hover:text-pink-300", light: "hover:text-pink-700" },
  { dark: "hover:text-pink-400", light: "hover:text-pink-600" },
  { dark: "hover:text-pink-500", light: "hover:text-pink-500" },
  { dark: "hover:text-pink-600", light: "hover:text-pink-400" },
  { dark: "hover:text-pink-700", light: "hover:text-pink-300" },
  { dark: "hover:text-pink-800", light: "hover:text-pink-200" },
  { dark: "hover:text-pink-900", light: "hover:text-pink-100" },
  { dark: "focus:text-neutral-000", light: "focus:text-neutral-1300" },
  { dark: "focus:text-neutral-100", light: "focus:text-neutral-1200" },
  { dark: "focus:text-neutral-200", light: "focus:text-neutral-1100" },
  { dark: "focus:text-neutral-300", light: "focus:text-neutral-1000" },
  { dark: "focus:text-neutral-400", light: "focus:text-neutral-900" },
  { dark: "focus:text-neutral-500", light: "focus:text-neutral-800" },
  { dark: "focus:text-neutral-600", light: "focus:text-neutral-700" },
  { dark: "focus:text-neutral-700", light: "focus:text-neutral-600" },
  { dark: "focus:text-neutral-800", light: "focus:text-neutral-500" },
  { dark: "focus:text-neutral-900", light: "focus:text-neutral-400" },
  { dark: "focus:text-neutral-1000", light: "focus:text-neutral-300" },
  { dark: "focus:text-neutral-1100", light: "focus:text-neutral-200" },
  { dark: "focus:text-neutral-1200", light: "focus:text-neutral-100" },
  { dark: "focus:text-neutral-1300", light: "focus:text-neutral-000" },
  { dark: "focus:text-orange-100", light: "focus:text-orange-1100" },
  { dark: "focus:text-orange-200", light: "focus:text-orange-1000" },
  { dark: "focus:text-orange-300", light: "focus:text-orange-900" },
  { dark: "focus:text-orange-400", light: "focus:text-orange-800" },
  { dark: "focus:text-orange-500", light: "focus:text-orange-700" },
  { dark: "focus:text-orange-600", light: "focus:text-orange-600" },
  { dark: "focus:text-orange-700", light: "focus:text-orange-500" },
  { dark: "focus:text-orange-800", light: "focus:text-orange-400" },
  { dark: "focus:text-orange-900", light: "focus:text-orange-300" },
  { dark: "focus:text-orange-1000", light: "focus:text-orange-200" },
  { dark: "focus:text-orange-1100", light: "focus:text-orange-100" },
  { dark: "focus:text-yellow-100", light: "focus:text-yellow-900" },
  { dark: "focus:text-yellow-200", light: "focus:text-yellow-800" },
  { dark: "focus:text-yellow-300", light: "focus:text-yellow-700" },
  { dark: "focus:text-yellow-400", light: "focus:text-yellow-600" },
  { dark: "focus:text-yellow-500", light: "focus:text-yellow-500" },
  { dark: "focus:text-yellow-600", light: "focus:text-yellow-400" },
  { dark: "focus:text-yellow-700", light: "focus:text-yellow-300" },
  { dark: "focus:text-yellow-800", light: "focus:text-yellow-200" },
  { dark: "focus:text-yellow-900", light: "focus:text-yellow-100" },
  { dark: "focus:text-green-100", light: "focus:text-green-900" },
  { dark: "focus:text-green-200", light: "focus:text-green-800" },
  { dark: "focus:text-green-300", light: "focus:text-green-700" },
  { dark: "focus:text-green-400", light: "focus:text-green-600" },
  { dark: "focus:text-green-500", light: "focus:text-green-500" },
  { dark: "focus:text-green-600", light: "focus:text-green-400" },
  { dark: "focus:text-green-700", light: "focus:text-green-300" },
  { dark: "focus:text-green-800", light: "focus:text-green-200" },
  { dark: "focus:text-green-900", light: "focus:text-green-100" },
  { dark: "focus:text-blue-100", light: "focus:text-blue-900" },
  { dark: "focus:text-blue-200", light: "focus:text-blue-800" },
  { dark: "focus:text-blue-300", light: "focus:text-blue-700" },
  { dark: "focus:text-blue-400", light: "focus:text-blue-600" },
  { dark: "focus:text-blue-500", light: "focus:text-blue-500" },
  { dark: "focus:text-blue-600", light: "focus:text-blue-400" },
  { dark: "focus:text-blue-700", light: "focus:text-blue-300" },
  { dark: "focus:text-blue-800", light: "focus:text-blue-200" },
  { dark: "focus:text-blue-900", light: "focus:text-blue-100" },
  { dark: "focus:text-violet-100", light: "focus:text-violet-900" },
  { dark: "focus:text-violet-200", light: "focus:text-violet-800" },
  { dark: "focus:text-violet-300", light: "focus:text-violet-700" },
  { dark: "focus:text-violet-400", light: "focus:text-violet-600" },
  { dark: "focus:text-violet-500", light: "focus:text-violet-500" },
  { dark: "focus:text-violet-600", light: "focus:text-violet-400" },
  { dark: "focus:text-violet-700", light: "focus:text-violet-300" },
  { dark: "focus:text-violet-800", light: "focus:text-violet-200" },
  { dark: "focus:text-violet-900", light: "focus:text-violet-100" },
  { dark: "focus:text-pink-100", light: "focus:text-pink-900" },
  { dark: "focus:text-pink-200", light: "focus:text-pink-800" },
  { dark: "focus:text-pink-300", light: "focus:text-pink-700" },
  { dark: "focus:text-pink-400", light: "focus:text-pink-600" },
  { dark: "focus:text-pink-500", light: "focus:text-pink-500" },
  { dark: "focus:text-pink-600", light: "focus:text-pink-400" },
  { dark: "focus:text-pink-700", light: "focus:text-pink-300" },
  { dark: "focus:text-pink-800", light: "focus:text-pink-200" },
  { dark: "focus:text-pink-900", light: "focus:text-pink-100" },
  {
    dark: "group-hover:text-neutral-000",
    light: "group-hover:text-neutral-1300",
  },
  {
    dark: "group-hover:text-neutral-100",
    light: "group-hover:text-neutral-1200",
  },
  {
    dark: "group-hover:text-neutral-200",
    light: "group-hover:text-neutral-1100",
  },
  {
    dark: "group-hover:text-neutral-300",
    light: "group-hover:text-neutral-1000",
  },
  {
    dark: "group-hover:text-neutral-400",
    light: "group-hover:text-neutral-900",
  },
  {
    dark: "group-hover:text-neutral-500",
    light: "group-hover:text-neutral-800",
  },
  {
    dark: "group-hover:text-neutral-600",
    light: "group-hover:text-neutral-700",
  },
  {
    dark: "group-hover:text-neutral-700",
    light: "group-hover:text-neutral-600",
  },
  {
    dark: "group-hover:text-neutral-800",
    light: "group-hover:text-neutral-500",
  },
  {
    dark: "group-hover:text-neutral-900",
    light: "group-hover:text-neutral-400",
  },
  {
    dark: "group-hover:text-neutral-1000",
    light: "group-hover:text-neutral-300",
  },
  {
    dark: "group-hover:text-neutral-1100",
    light: "group-hover:text-neutral-200",
  },
  {
    dark: "group-hover:text-neutral-1200",
    light: "group-hover:text-neutral-100",
  },
  {
    dark: "group-hover:text-neutral-1300",
    light: "group-hover:text-neutral-000",
  },
  {
    dark: "group-hover:text-orange-100",
    light: "group-hover:text-orange-1100",
  },
  {
    dark: "group-hover:text-orange-200",
    light: "group-hover:text-orange-1000",
  },
  { dark: "group-hover:text-orange-300", light: "group-hover:text-orange-900" },
  { dark: "group-hover:text-orange-400", light: "group-hover:text-orange-800" },
  { dark: "group-hover:text-orange-500", light: "group-hover:text-orange-700" },
  { dark: "group-hover:text-orange-600", light: "group-hover:text-orange-600" },
  { dark: "group-hover:text-orange-700", light: "group-hover:text-orange-500" },
  { dark: "group-hover:text-orange-800", light: "group-hover:text-orange-400" },
  { dark: "group-hover:text-orange-900", light: "group-hover:text-orange-300" },
  {
    dark: "group-hover:text-orange-1000",
    light: "group-hover:text-orange-200",
  },
  {
    dark: "group-hover:text-orange-1100",
    light: "group-hover:text-orange-100",
  },
  { dark: "group-hover:text-yellow-100", light: "group-hover:text-yellow-900" },
  { dark: "group-hover:text-yellow-200", light: "group-hover:text-yellow-800" },
  { dark: "group-hover:text-yellow-300", light: "group-hover:text-yellow-700" },
  { dark: "group-hover:text-yellow-400", light: "group-hover:text-yellow-600" },
  { dark: "group-hover:text-yellow-500", light: "group-hover:text-yellow-500" },
  { dark: "group-hover:text-yellow-600", light: "group-hover:text-yellow-400" },
  { dark: "group-hover:text-yellow-700", light: "group-hover:text-yellow-300" },
  { dark: "group-hover:text-yellow-800", light: "group-hover:text-yellow-200" },
  { dark: "group-hover:text-yellow-900", light: "group-hover:text-yellow-100" },
  { dark: "group-hover:text-green-100", light: "group-hover:text-green-900" },
  { dark: "group-hover:text-green-200", light: "group-hover:text-green-800" },
  { dark: "group-hover:text-green-300", light: "group-hover:text-green-700" },
  { dark: "group-hover:text-green-400", light: "group-hover:text-green-600" },
  { dark: "group-hover:text-green-500", light: "group-hover:text-green-500" },
  { dark: "group-hover:text-green-600", light: "group-hover:text-green-400" },
  { dark: "group-hover:text-green-700", light: "group-hover:text-green-300" },
  { dark: "group-hover:text-green-800", light: "group-hover:text-green-200" },
  { dark: "group-hover:text-green-900", light: "group-hover:text-green-100" },
  { dark: "group-hover:text-blue-100", light: "group-hover:text-blue-900" },
  { dark: "group-hover:text-blue-200", light: "group-hover:text-blue-800" },
  { dark: "group-hover:text-blue-300", light: "group-hover:text-blue-700" },
  { dark: "group-hover:text-blue-400", light: "group-hover:text-blue-600" },
  { dark: "group-hover:text-blue-500", light: "group-hover:text-blue-500" },
  { dark: "group-hover:text-blue-600", light: "group-hover:text-blue-400" },
  { dark: "group-hover:text-blue-700", light: "group-hover:text-blue-300" },
  { dark: "group-hover:text-blue-800", light: "group-hover:text-blue-200" },
  { dark: "group-hover:text-blue-900", light: "group-hover:text-blue-100" },
  { dark: "group-hover:text-violet-100", light: "group-hover:text-violet-900" },
  { dark: "group-hover:text-violet-200", light: "group-hover:text-violet-800" },
  { dark: "group-hover:text-violet-300", light: "group-hover:text-violet-700" },
  { dark: "group-hover:text-violet-400", light: "group-hover:text-violet-600" },
  { dark: "group-hover:text-violet-500", light: "group-hover:text-violet-500" },
  { dark: "group-hover:text-violet-600", light: "group-hover:text-violet-400" },
  { dark: "group-hover:text-violet-700", light: "group-hover:text-violet-300" },
  { dark: "group-hover:text-violet-800", light: "group-hover:text-violet-200" },
  { dark: "group-hover:text-violet-900", light: "group-hover:text-violet-100" },
  { dark: "group-hover:text-pink-100", light: "group-hover:text-pink-900" },
  { dark: "group-hover:text-pink-200", light: "group-hover:text-pink-800" },
  { dark: "group-hover:text-pink-300", light: "group-hover:text-pink-700" },
  { dark: "group-hover:text-pink-400", light: "group-hover:text-pink-600" },
  { dark: "group-hover:text-pink-500", light: "group-hover:text-pink-500" },
  { dark: "group-hover:text-pink-600", light: "group-hover:text-pink-400" },
  { dark: "group-hover:text-pink-700", light: "group-hover:text-pink-300" },
  { dark: "group-hover:text-pink-800", light: "group-hover:text-pink-200" },
  { dark: "group-hover:text-pink-900", light: "group-hover:text-pink-100" },
];

const bgColorMappings: { dark: ColorClass; light: ColorClass }[] = [
  { dark: "bg-neutral-000", light: "bg-neutral-1300" },
  { dark: "bg-neutral-100", light: "bg-neutral-1200" },
  { dark: "bg-neutral-200", light: "bg-neutral-1100" },
  { dark: "bg-neutral-300", light: "bg-neutral-1000" },
  { dark: "bg-neutral-400", light: "bg-neutral-900" },
  { dark: "bg-neutral-500", light: "bg-neutral-800" },
  { dark: "bg-neutral-600", light: "bg-neutral-700" },
  { dark: "bg-neutral-700", light: "bg-neutral-600" },
  { dark: "bg-neutral-800", light: "bg-neutral-500" },
  { dark: "bg-neutral-900", light: "bg-neutral-400" },
  { dark: "bg-neutral-1000", light: "bg-neutral-300" },
  { dark: "bg-neutral-1100", light: "bg-neutral-200" },
  { dark: "bg-neutral-1200", light: "bg-neutral-100" },
  { dark: "bg-neutral-1300", light: "bg-neutral-000" },
  { dark: "bg-orange-100", light: "bg-orange-1100" },
  { dark: "bg-orange-200", light: "bg-orange-1000" },
  { dark: "bg-orange-300", light: "bg-orange-900" },
  { dark: "bg-orange-400", light: "bg-orange-800" },
  { dark: "bg-orange-500", light: "bg-orange-700" },
  { dark: "bg-orange-600", light: "bg-orange-600" },
  { dark: "bg-orange-700", light: "bg-orange-500" },
  { dark: "bg-orange-800", light: "bg-orange-400" },
  { dark: "bg-orange-900", light: "bg-orange-300" },
  { dark: "bg-orange-1000", light: "bg-orange-200" },
  { dark: "bg-orange-1100", light: "bg-orange-100" },
  { dark: "bg-yellow-100", light: "bg-yellow-900" },
  { dark: "bg-yellow-200", light: "bg-yellow-800" },
  { dark: "bg-yellow-300", light: "bg-yellow-700" },
  { dark: "bg-yellow-400", light: "bg-yellow-600" },
  { dark: "bg-yellow-500", light: "bg-yellow-500" },
  { dark: "bg-yellow-600", light: "bg-yellow-400" },
  { dark: "bg-yellow-700", light: "bg-yellow-300" },
  { dark: "bg-yellow-800", light: "bg-yellow-200" },
  { dark: "bg-yellow-900", light: "bg-yellow-100" },
  { dark: "bg-green-100", light: "bg-green-900" },
  { dark: "bg-green-200", light: "bg-green-800" },
  { dark: "bg-green-300", light: "bg-green-700" },
  { dark: "bg-green-400", light: "bg-green-600" },
  { dark: "bg-green-500", light: "bg-green-500" },
  { dark: "bg-green-600", light: "bg-green-400" },
  { dark: "bg-green-700", light: "bg-green-300" },
  { dark: "bg-green-800", light: "bg-green-200" },
  { dark: "bg-green-900", light: "bg-green-100" },
  { dark: "bg-blue-100", light: "bg-blue-900" },
  { dark: "bg-blue-200", light: "bg-blue-800" },
  { dark: "bg-blue-300", light: "bg-blue-700" },
  { dark: "bg-blue-400", light: "bg-blue-600" },
  { dark: "bg-blue-500", light: "bg-blue-500" },
  { dark: "bg-blue-600", light: "bg-blue-400" },
  { dark: "bg-blue-700", light: "bg-blue-300" },
  { dark: "bg-blue-800", light: "bg-blue-200" },
  { dark: "bg-blue-900", light: "bg-blue-100" },
  { dark: "bg-violet-100", light: "bg-violet-900" },
  { dark: "bg-violet-200", light: "bg-violet-800" },
  { dark: "bg-violet-300", light: "bg-violet-700" },
  { dark: "bg-violet-400", light: "bg-violet-600" },
  { dark: "bg-violet-500", light: "bg-violet-500" },
  { dark: "bg-violet-600", light: "bg-violet-400" },
  { dark: "bg-violet-700", light: "bg-violet-300" },
  { dark: "bg-violet-800", light: "bg-violet-200" },
  { dark: "bg-violet-900", light: "bg-violet-100" },
  { dark: "bg-pink-100", light: "bg-pink-900" },
  { dark: "bg-pink-200", light: "bg-pink-800" },
  { dark: "bg-pink-300", light: "bg-pink-700" },
  { dark: "bg-pink-400", light: "bg-pink-600" },
  { dark: "bg-pink-500", light: "bg-pink-500" },
  { dark: "bg-pink-600", light: "bg-pink-400" },
  { dark: "bg-pink-700", light: "bg-pink-300" },
  { dark: "bg-pink-800", light: "bg-pink-200" },
  { dark: "bg-pink-900", light: "bg-pink-100" },
  { dark: "hover:bg-neutral-000", light: "hover:bg-neutral-1300" },
  { dark: "hover:bg-neutral-100", light: "hover:bg-neutral-1200" },
  { dark: "hover:bg-neutral-200", light: "hover:bg-neutral-1100" },
  { dark: "hover:bg-neutral-300", light: "hover:bg-neutral-1000" },
  { dark: "hover:bg-neutral-400", light: "hover:bg-neutral-900" },
  { dark: "hover:bg-neutral-500", light: "hover:bg-neutral-800" },
  { dark: "hover:bg-neutral-600", light: "hover:bg-neutral-700" },
  { dark: "hover:bg-neutral-700", light: "hover:bg-neutral-600" },
  { dark: "hover:bg-neutral-800", light: "hover:bg-neutral-500" },
  { dark: "hover:bg-neutral-900", light: "hover:bg-neutral-400" },
  { dark: "hover:bg-neutral-1000", light: "hover:bg-neutral-300" },
  { dark: "hover:bg-neutral-1100", light: "hover:bg-neutral-200" },
  { dark: "hover:bg-neutral-1200", light: "hover:bg-neutral-100" },
  { dark: "hover:bg-neutral-1300", light: "hover:bg-neutral-000" },
  { dark: "hover:bg-orange-100", light: "hover:bg-orange-1100" },
  { dark: "hover:bg-orange-200", light: "hover:bg-orange-1000" },
  { dark: "hover:bg-orange-300", light: "hover:bg-orange-900" },
  { dark: "hover:bg-orange-400", light: "hover:bg-orange-800" },
  { dark: "hover:bg-orange-500", light: "hover:bg-orange-700" },
  { dark: "hover:bg-orange-600", light: "hover:bg-orange-600" },
  { dark: "hover:bg-orange-700", light: "hover:bg-orange-500" },
  { dark: "hover:bg-orange-800", light: "hover:bg-orange-400" },
  { dark: "hover:bg-orange-900", light: "hover:bg-orange-300" },
  { dark: "hover:bg-orange-1000", light: "hover:bg-orange-200" },
  { dark: "hover:bg-orange-1100", light: "hover:bg-orange-100" },
  { dark: "hover:bg-yellow-100", light: "hover:bg-yellow-900" },
  { dark: "hover:bg-yellow-200", light: "hover:bg-yellow-800" },
  { dark: "hover:bg-yellow-300", light: "hover:bg-yellow-700" },
  { dark: "hover:bg-yellow-400", light: "hover:bg-yellow-600" },
  { dark: "hover:bg-yellow-500", light: "hover:bg-yellow-500" },
  { dark: "hover:bg-yellow-600", light: "hover:bg-yellow-400" },
  { dark: "hover:bg-yellow-700", light: "hover:bg-yellow-300" },
  { dark: "hover:bg-yellow-800", light: "hover:bg-yellow-200" },
  { dark: "hover:bg-yellow-900", light: "hover:bg-yellow-100" },
  { dark: "hover:bg-green-100", light: "hover:bg-green-900" },
  { dark: "hover:bg-green-200", light: "hover:bg-green-800" },
  { dark: "hover:bg-green-300", light: "hover:bg-green-700" },
  { dark: "hover:bg-green-400", light: "hover:bg-green-600" },
  { dark: "hover:bg-green-500", light: "hover:bg-green-500" },
  { dark: "hover:bg-green-600", light: "hover:bg-green-400" },
  { dark: "hover:bg-green-700", light: "hover:bg-green-300" },
  { dark: "hover:bg-green-800", light: "hover:bg-green-200" },
  { dark: "hover:bg-green-900", light: "hover:bg-green-100" },
  { dark: "hover:bg-blue-100", light: "hover:bg-blue-900" },
  { dark: "hover:bg-blue-200", light: "hover:bg-blue-800" },
  { dark: "hover:bg-blue-300", light: "hover:bg-blue-700" },
  { dark: "hover:bg-blue-400", light: "hover:bg-blue-600" },
  { dark: "hover:bg-blue-500", light: "hover:bg-blue-500" },
  { dark: "hover:bg-blue-600", light: "hover:bg-blue-400" },
  { dark: "hover:bg-blue-700", light: "hover:bg-blue-300" },
  { dark: "hover:bg-blue-800", light: "hover:bg-blue-200" },
  { dark: "hover:bg-blue-900", light: "hover:bg-blue-100" },
  { dark: "hover:bg-violet-100", light: "hover:bg-violet-900" },
  { dark: "hover:bg-violet-200", light: "hover:bg-violet-800" },
  { dark: "hover:bg-violet-300", light: "hover:bg-violet-700" },
  { dark: "hover:bg-violet-400", light: "hover:bg-violet-600" },
  { dark: "hover:bg-violet-500", light: "hover:bg-violet-500" },
  { dark: "hover:bg-violet-600", light: "hover:bg-violet-400" },
  { dark: "hover:bg-violet-700", light: "hover:bg-violet-300" },
  { dark: "hover:bg-violet-800", light: "hover:bg-violet-200" },
  { dark: "hover:bg-violet-900", light: "hover:bg-violet-100" },
  { dark: "hover:bg-pink-100", light: "hover:bg-pink-900" },
  { dark: "hover:bg-pink-200", light: "hover:bg-pink-800" },
  { dark: "hover:bg-pink-300", light: "hover:bg-pink-700" },
  { dark: "hover:bg-pink-400", light: "hover:bg-pink-600" },
  { dark: "hover:bg-pink-500", light: "hover:bg-pink-500" },
  { dark: "hover:bg-pink-600", light: "hover:bg-pink-400" },
  { dark: "hover:bg-pink-700", light: "hover:bg-pink-300" },
  { dark: "hover:bg-pink-800", light: "hover:bg-pink-200" },
  { dark: "hover:bg-pink-900", light: "hover:bg-pink-100" },

  { dark: "focus:bg-neutral-000", light: "focus:bg-neutral-1300" },
  { dark: "focus:bg-neutral-100", light: "focus:bg-neutral-1200" },
  { dark: "focus:bg-neutral-200", light: "focus:bg-neutral-1100" },
  { dark: "focus:bg-neutral-300", light: "focus:bg-neutral-1000" },
  { dark: "focus:bg-neutral-400", light: "focus:bg-neutral-900" },
  { dark: "focus:bg-neutral-500", light: "focus:bg-neutral-800" },
  { dark: "focus:bg-neutral-600", light: "focus:bg-neutral-700" },
  { dark: "focus:bg-neutral-700", light: "focus:bg-neutral-600" },
  { dark: "focus:bg-neutral-800", light: "focus:bg-neutral-500" },
  { dark: "focus:bg-neutral-900", light: "focus:bg-neutral-400" },
  { dark: "focus:bg-neutral-1000", light: "focus:bg-neutral-300" },
  { dark: "focus:bg-neutral-1100", light: "focus:bg-neutral-200" },
  { dark: "focus:bg-neutral-1200", light: "focus:bg-neutral-100" },
  { dark: "focus:bg-neutral-1300", light: "focus:bg-neutral-000" },
  { dark: "focus:bg-orange-100", light: "focus:bg-orange-1100" },
  { dark: "focus:bg-orange-200", light: "focus:bg-orange-1000" },
  { dark: "focus:bg-orange-300", light: "focus:bg-orange-900" },
  { dark: "focus:bg-orange-400", light: "focus:bg-orange-800" },
  { dark: "focus:bg-orange-500", light: "focus:bg-orange-700" },
  { dark: "focus:bg-orange-600", light: "focus:bg-orange-600" },
  { dark: "focus:bg-orange-700", light: "focus:bg-orange-500" },
  { dark: "focus:bg-orange-800", light: "focus:bg-orange-400" },
  { dark: "focus:bg-orange-900", light: "focus:bg-orange-300" },
  { dark: "focus:bg-orange-1000", light: "focus:bg-orange-200" },
  { dark: "focus:bg-orange-1100", light: "focus:bg-orange-100" },
  { dark: "focus:bg-yellow-100", light: "focus:bg-yellow-900" },
  { dark: "focus:bg-yellow-200", light: "focus:bg-yellow-800" },
  { dark: "focus:bg-yellow-300", light: "focus:bg-yellow-700" },
  { dark: "focus:bg-yellow-400", light: "focus:bg-yellow-600" },
  { dark: "focus:bg-yellow-500", light: "focus:bg-yellow-500" },
  { dark: "focus:bg-yellow-600", light: "focus:bg-yellow-400" },
  { dark: "focus:bg-yellow-700", light: "focus:bg-yellow-300" },
  { dark: "focus:bg-yellow-800", light: "focus:bg-yellow-200" },
  { dark: "focus:bg-yellow-900", light: "focus:bg-yellow-100" },
  { dark: "focus:bg-green-100", light: "focus:bg-green-900" },
  { dark: "focus:bg-green-200", light: "focus:bg-green-800" },
  { dark: "focus:bg-green-300", light: "focus:bg-green-700" },
  { dark: "focus:bg-green-400", light: "focus:bg-green-600" },
  { dark: "focus:bg-green-500", light: "focus:bg-green-500" },
  { dark: "focus:bg-green-600", light: "focus:bg-green-400" },
  { dark: "focus:bg-green-700", light: "focus:bg-green-300" },
  { dark: "focus:bg-green-800", light: "focus:bg-green-200" },
  { dark: "focus:bg-green-900", light: "focus:bg-green-100" },
  { dark: "focus:bg-blue-100", light: "focus:bg-blue-900" },
  { dark: "focus:bg-blue-200", light: "focus:bg-blue-800" },
  { dark: "focus:bg-blue-300", light: "focus:bg-blue-700" },
  { dark: "focus:bg-blue-400", light: "focus:bg-blue-600" },
  { dark: "focus:bg-blue-500", light: "focus:bg-blue-500" },
  { dark: "focus:bg-blue-600", light: "focus:bg-blue-400" },
  { dark: "focus:bg-blue-700", light: "focus:bg-blue-300" },
  { dark: "focus:bg-blue-800", light: "focus:bg-blue-200" },
  { dark: "focus:bg-blue-900", light: "focus:bg-blue-100" },
  { dark: "focus:bg-violet-100", light: "focus:bg-violet-900" },
  { dark: "focus:bg-violet-200", light: "focus:bg-violet-800" },
  { dark: "focus:bg-violet-300", light: "focus:bg-violet-700" },
  { dark: "focus:bg-violet-400", light: "focus:bg-violet-600" },
  { dark: "focus:bg-violet-500", light: "focus:bg-violet-500" },
  { dark: "focus:bg-violet-600", light: "focus:bg-violet-400" },
  { dark: "focus:bg-violet-700", light: "focus:bg-violet-300" },
  { dark: "focus:bg-violet-800", light: "focus:bg-violet-200" },
  { dark: "focus:bg-violet-900", light: "focus:bg-violet-100" },
  { dark: "focus:bg-pink-100", light: "focus:bg-pink-900" },
  { dark: "focus:bg-pink-200", light: "focus:bg-pink-800" },
  { dark: "focus:bg-pink-300", light: "focus:bg-pink-700" },
  { dark: "focus:bg-pink-400", light: "focus:bg-pink-600" },
  { dark: "focus:bg-pink-500", light: "focus:bg-pink-500" },
  { dark: "focus:bg-pink-600", light: "focus:bg-pink-400" },
  { dark: "focus:bg-pink-700", light: "focus:bg-pink-300" },
  { dark: "focus:bg-pink-800", light: "focus:bg-pink-200" },
  { dark: "focus:bg-pink-900", light: "focus:bg-pink-100" },

  { dark: "group-hover:bg-neutral-000", light: "group-hover:bg-neutral-1300" },
  { dark: "group-hover:bg-neutral-100", light: "group-hover:bg-neutral-1200" },
  { dark: "group-hover:bg-neutral-200", light: "group-hover:bg-neutral-1100" },
  { dark: "group-hover:bg-neutral-300", light: "group-hover:bg-neutral-1000" },
  { dark: "group-hover:bg-neutral-400", light: "group-hover:bg-neutral-900" },
  { dark: "group-hover:bg-neutral-500", light: "group-hover:bg-neutral-800" },
  { dark: "group-hover:bg-neutral-600", light: "group-hover:bg-neutral-700" },
  { dark: "group-hover:bg-neutral-700", light: "group-hover:bg-neutral-600" },
  { dark: "group-hover:bg-neutral-800", light: "group-hover:bg-neutral-500" },
  { dark: "group-hover:bg-neutral-900", light: "group-hover:bg-neutral-400" },
  { dark: "group-hover:bg-neutral-1000", light: "group-hover:bg-neutral-300" },
  { dark: "group-hover:bg-neutral-1100", light: "group-hover:bg-neutral-200" },
  { dark: "group-hover:bg-neutral-1200", light: "group-hover:bg-neutral-100" },
  { dark: "group-hover:bg-neutral-1300", light: "group-hover:bg-neutral-000" },
  { dark: "group-hover:bg-orange-100", light: "group-hover:bg-orange-1100" },
  { dark: "group-hover:bg-orange-200", light: "group-hover:bg-orange-1000" },
  { dark: "group-hover:bg-orange-300", light: "group-hover:bg-orange-900" },
  { dark: "group-hover:bg-orange-400", light: "group-hover:bg-orange-800" },
  { dark: "group-hover:bg-orange-500", light: "group-hover:bg-orange-700" },
  { dark: "group-hover:bg-orange-600", light: "group-hover:bg-orange-600" },
  { dark: "group-hover:bg-orange-700", light: "group-hover:bg-orange-500" },
  { dark: "group-hover:bg-orange-800", light: "group-hover:bg-orange-400" },
  { dark: "group-hover:bg-orange-900", light: "group-hover:bg-orange-300" },
  { dark: "group-hover:bg-orange-1000", light: "group-hover:bg-orange-200" },
  { dark: "group-hover:bg-orange-1100", light: "group-hover:bg-orange-100" },
  { dark: "group-hover:bg-yellow-100", light: "group-hover:bg-yellow-900" },
  { dark: "group-hover:bg-yellow-200", light: "group-hover:bg-yellow-800" },
  { dark: "group-hover:bg-yellow-300", light: "group-hover:bg-yellow-700" },
  { dark: "group-hover:bg-yellow-400", light: "group-hover:bg-yellow-600" },
  { dark: "group-hover:bg-yellow-500", light: "group-hover:bg-yellow-500" },
  { dark: "group-hover:bg-yellow-600", light: "group-hover:bg-yellow-400" },
  { dark: "group-hover:bg-yellow-700", light: "group-hover:bg-yellow-300" },
  { dark: "group-hover:bg-yellow-800", light: "group-hover:bg-yellow-200" },
  { dark: "group-hover:bg-yellow-900", light: "group-hover:bg-yellow-100" },
  { dark: "group-hover:bg-green-100", light: "group-hover:bg-green-900" },
  { dark: "group-hover:bg-green-200", light: "group-hover:bg-green-800" },
  { dark: "group-hover:bg-green-300", light: "group-hover:bg-green-700" },
  { dark: "group-hover:bg-green-400", light: "group-hover:bg-green-600" },
  { dark: "group-hover:bg-green-500", light: "group-hover:bg-green-500" },
  { dark: "group-hover:bg-green-600", light: "group-hover:bg-green-400" },
  { dark: "group-hover:bg-green-700", light: "group-hover:bg-green-300" },
  { dark: "group-hover:bg-green-800", light: "group-hover:bg-green-200" },
  { dark: "group-hover:bg-green-900", light: "group-hover:bg-green-100" },
  { dark: "group-hover:bg-blue-100", light: "group-hover:bg-blue-900" },
  { dark: "group-hover:bg-blue-200", light: "group-hover:bg-blue-800" },
  { dark: "group-hover:bg-blue-300", light: "group-hover:bg-blue-700" },
  { dark: "group-hover:bg-blue-400", light: "group-hover:bg-blue-600" },
  { dark: "group-hover:bg-blue-500", light: "group-hover:bg-blue-500" },
  { dark: "group-hover:bg-blue-600", light: "group-hover:bg-blue-400" },
  { dark: "group-hover:bg-blue-700", light: "group-hover:bg-blue-300" },
  { dark: "group-hover:bg-blue-800", light: "group-hover:bg-blue-200" },
  { dark: "group-hover:bg-blue-900", light: "group-hover:bg-blue-100" },
  { dark: "group-hover:bg-violet-100", light: "group-hover:bg-violet-900" },
  { dark: "group-hover:bg-violet-200", light: "group-hover:bg-violet-800" },
  { dark: "group-hover:bg-violet-300", light: "group-hover:bg-violet-700" },
  { dark: "group-hover:bg-violet-400", light: "group-hover:bg-violet-600" },
  { dark: "group-hover:bg-violet-500", light: "group-hover:bg-violet-500" },
  { dark: "group-hover:bg-violet-600", light: "group-hover:bg-violet-400" },
  { dark: "group-hover:bg-violet-700", light: "group-hover:bg-violet-300" },
  { dark: "group-hover:bg-violet-800", light: "group-hover:bg-violet-200" },
  { dark: "group-hover:bg-violet-900", light: "group-hover:bg-violet-100" },
  { dark: "group-hover:bg-pink-100", light: "group-hover:bg-pink-900" },
  { dark: "group-hover:bg-pink-200", light: "group-hover:bg-pink-800" },
  { dark: "group-hover:bg-pink-300", light: "group-hover:bg-pink-700" },
  { dark: "group-hover:bg-pink-400", light: "group-hover:bg-pink-600" },
  { dark: "group-hover:bg-pink-500", light: "group-hover:bg-pink-500" },
  { dark: "group-hover:bg-pink-600", light: "group-hover:bg-pink-400" },
  { dark: "group-hover:bg-pink-700", light: "group-hover:bg-pink-300" },
  { dark: "group-hover:bg-pink-800", light: "group-hover:bg-pink-200" },
  { dark: "group-hover:bg-pink-900", light: "group-hover:bg-pink-100" },
];

const additionalColorMappings: { dark: ColorClass; light: ColorClass }[] = [
  { dark: "from-neutral-000", light: "from-neutral-1300" },
  { dark: "from-neutral-100", light: "from-neutral-1200" },
  { dark: "from-neutral-200", light: "from-neutral-1100" },
  { dark: "from-neutral-300", light: "from-neutral-1000" },
  { dark: "from-neutral-400", light: "from-neutral-900" },
  { dark: "from-neutral-500", light: "from-neutral-800" },
  { dark: "from-neutral-600", light: "from-neutral-700" },
  { dark: "from-neutral-700", light: "from-neutral-600" },
  { dark: "from-neutral-800", light: "from-neutral-500" },
  { dark: "from-neutral-900", light: "from-neutral-400" },
  { dark: "from-neutral-1000", light: "from-neutral-300" },
  { dark: "from-neutral-1100", light: "from-neutral-200" },
  { dark: "from-neutral-1200", light: "from-neutral-100" },
  { dark: "from-neutral-1300", light: "from-neutral-000" },
  { dark: "from-orange-100", light: "from-orange-1100" },
  { dark: "from-orange-200", light: "from-orange-1000" },
  { dark: "from-orange-300", light: "from-orange-900" },
  { dark: "from-orange-400", light: "from-orange-800" },
  { dark: "from-orange-500", light: "from-orange-700" },
  { dark: "from-orange-600", light: "from-orange-600" },
  { dark: "from-orange-700", light: "from-orange-500" },
  { dark: "from-orange-800", light: "from-orange-400" },
  { dark: "from-orange-900", light: "from-orange-300" },
  { dark: "from-orange-1000", light: "from-orange-200" },
  { dark: "from-orange-1100", light: "from-orange-100" },
  { dark: "from-yellow-100", light: "from-yellow-900" },
  { dark: "from-yellow-200", light: "from-yellow-800" },
  { dark: "from-yellow-300", light: "from-yellow-700" },
  { dark: "from-yellow-400", light: "from-yellow-600" },
  { dark: "from-yellow-500", light: "from-yellow-500" },
  { dark: "from-yellow-600", light: "from-yellow-400" },
  { dark: "from-yellow-700", light: "from-yellow-300" },
  { dark: "from-yellow-800", light: "from-yellow-200" },
  { dark: "from-yellow-900", light: "from-yellow-100" },
  { dark: "from-green-100", light: "from-green-900" },
  { dark: "from-green-200", light: "from-green-800" },
  { dark: "from-green-300", light: "from-green-700" },
  { dark: "from-green-400", light: "from-green-600" },
  { dark: "from-green-500", light: "from-green-500" },
  { dark: "from-green-600", light: "from-green-400" },
  { dark: "from-green-700", light: "from-green-300" },
  { dark: "from-green-800", light: "from-green-200" },
  { dark: "from-green-900", light: "from-green-100" },
  { dark: "from-blue-100", light: "from-blue-900" },
  { dark: "from-blue-200", light: "from-blue-800" },
  { dark: "from-blue-300", light: "from-blue-700" },
  { dark: "from-blue-400", light: "from-blue-600" },
  { dark: "from-blue-500", light: "from-blue-500" },
  { dark: "from-blue-600", light: "from-blue-400" },
  { dark: "from-blue-700", light: "from-blue-300" },
  { dark: "from-blue-800", light: "from-blue-200" },
  { dark: "from-blue-900", light: "from-blue-100" },
  { dark: "from-violet-100", light: "from-violet-900" },
  { dark: "from-violet-200", light: "from-violet-800" },
  { dark: "from-violet-300", light: "from-violet-700" },
  { dark: "from-violet-400", light: "from-violet-600" },
  { dark: "from-violet-500", light: "from-violet-500" },
  { dark: "from-violet-600", light: "from-violet-400" },
  { dark: "from-violet-700", light: "from-violet-300" },
  { dark: "from-violet-800", light: "from-violet-200" },
  { dark: "from-violet-900", light: "from-violet-100" },
  { dark: "from-pink-100", light: "from-pink-900" },
  { dark: "from-pink-200", light: "from-pink-800" },
  { dark: "from-pink-300", light: "from-pink-700" },
  { dark: "from-pink-400", light: "from-pink-600" },
  { dark: "from-pink-500", light: "from-pink-500" },
  { dark: "from-pink-600", light: "from-pink-400" },
  { dark: "from-pink-700", light: "from-pink-300" },
  { dark: "from-pink-800", light: "from-pink-200" },
  { dark: "from-pink-900", light: "from-pink-100" },

  { dark: "to-neutral-000", light: "to-neutral-1300" },
  { dark: "to-neutral-100", light: "to-neutral-1200" },
  { dark: "to-neutral-200", light: "to-neutral-1100" },
  { dark: "to-neutral-300", light: "to-neutral-1000" },
  { dark: "to-neutral-400", light: "to-neutral-900" },
  { dark: "to-neutral-500", light: "to-neutral-800" },
  { dark: "to-neutral-600", light: "to-neutral-700" },
  { dark: "to-neutral-700", light: "to-neutral-600" },
  { dark: "to-neutral-800", light: "to-neutral-500" },
  { dark: "to-neutral-900", light: "to-neutral-400" },
  { dark: "to-neutral-1000", light: "to-neutral-300" },
  { dark: "to-neutral-1100", light: "to-neutral-200" },
  { dark: "to-neutral-1200", light: "to-neutral-100" },
  { dark: "to-neutral-1300", light: "to-neutral-000" },
  { dark: "to-orange-100", light: "to-orange-1100" },
  { dark: "to-orange-200", light: "to-orange-1000" },
  { dark: "to-orange-300", light: "to-orange-900" },
  { dark: "to-orange-400", light: "to-orange-800" },
  { dark: "to-orange-500", light: "to-orange-700" },
  { dark: "to-orange-600", light: "to-orange-600" },
  { dark: "to-orange-700", light: "to-orange-500" },
  { dark: "to-orange-800", light: "to-orange-400" },
  { dark: "to-orange-900", light: "to-orange-300" },
  { dark: "to-orange-1000", light: "to-orange-200" },
  { dark: "to-orange-1100", light: "to-orange-100" },
  { dark: "to-yellow-100", light: "to-yellow-900" },
  { dark: "to-yellow-200", light: "to-yellow-800" },
  { dark: "to-yellow-300", light: "to-yellow-700" },
  { dark: "to-yellow-400", light: "to-yellow-600" },
  { dark: "to-yellow-500", light: "to-yellow-500" },
  { dark: "to-yellow-600", light: "to-yellow-400" },
  { dark: "to-yellow-700", light: "to-yellow-300" },
  { dark: "to-yellow-800", light: "to-yellow-200" },
  { dark: "to-yellow-900", light: "to-yellow-100" },
  { dark: "to-green-100", light: "to-green-900" },
  { dark: "to-green-200", light: "to-green-800" },
  { dark: "to-green-300", light: "to-green-700" },
  { dark: "to-green-400", light: "to-green-600" },
  { dark: "to-green-500", light: "to-green-500" },
  { dark: "to-green-600", light: "to-green-400" },
  { dark: "to-green-700", light: "to-green-300" },
  { dark: "to-green-800", light: "to-green-200" },
  { dark: "to-green-900", light: "to-green-100" },
  { dark: "to-blue-100", light: "to-blue-900" },
  { dark: "to-blue-200", light: "to-blue-800" },
  { dark: "to-blue-300", light: "to-blue-700" },
  { dark: "to-blue-400", light: "to-blue-600" },
  { dark: "to-blue-500", light: "to-blue-500" },
  { dark: "to-blue-600", light: "to-blue-400" },
  { dark: "to-blue-700", light: "to-blue-300" },
  { dark: "to-blue-800", light: "to-blue-200" },
  { dark: "to-blue-900", light: "to-blue-100" },
  { dark: "to-violet-100", light: "to-violet-900" },
  { dark: "to-violet-200", light: "to-violet-800" },
  { dark: "to-violet-300", light: "to-violet-700" },
  { dark: "to-violet-400", light: "to-violet-600" },
  { dark: "to-violet-500", light: "to-violet-500" },
  { dark: "to-violet-600", light: "to-violet-400" },
  { dark: "to-violet-700", light: "to-violet-300" },
  { dark: "to-violet-800", light: "to-violet-200" },
  { dark: "to-violet-900", light: "to-violet-100" },
  { dark: "to-pink-100", light: "to-pink-900" },
  { dark: "to-pink-200", light: "to-pink-800" },
  { dark: "to-pink-300", light: "to-pink-700" },
  { dark: "to-pink-400", light: "to-pink-600" },
  { dark: "to-pink-500", light: "to-pink-500" },
  { dark: "to-pink-600", light: "to-pink-400" },
  { dark: "to-pink-700", light: "to-pink-300" },
  { dark: "to-pink-800", light: "to-pink-200" },
  { dark: "to-pink-900", light: "to-pink-100" },

  { dark: "border-neutral-000", light: "border-neutral-1300" },
  { dark: "border-neutral-100", light: "border-neutral-1200" },
  { dark: "border-neutral-200", light: "border-neutral-1100" },
  { dark: "border-neutral-300", light: "border-neutral-1000" },
  { dark: "border-neutral-400", light: "border-neutral-900" },
  { dark: "border-neutral-500", light: "border-neutral-800" },
  { dark: "border-neutral-600", light: "border-neutral-700" },
  { dark: "border-neutral-700", light: "border-neutral-600" },
  { dark: "border-neutral-800", light: "border-neutral-500" },
  { dark: "border-neutral-900", light: "border-neutral-400" },
  { dark: "border-neutral-1000", light: "border-neutral-300" },
  { dark: "border-neutral-1100", light: "border-neutral-200" },
  { dark: "border-neutral-1200", light: "border-neutral-100" },
  { dark: "border-neutral-1300", light: "border-neutral-000" },
  { dark: "border-orange-100", light: "border-orange-1100" },
  { dark: "border-orange-200", light: "border-orange-1000" },
  { dark: "border-orange-300", light: "border-orange-900" },
  { dark: "border-orange-400", light: "border-orange-800" },
  { dark: "border-orange-500", light: "border-orange-700" },
  { dark: "border-orange-600", light: "border-orange-600" },
  { dark: "border-orange-700", light: "border-orange-500" },
  { dark: "border-orange-800", light: "border-orange-400" },
  { dark: "border-orange-900", light: "border-orange-300" },
  { dark: "border-orange-1000", light: "border-orange-200" },
  { dark: "border-orange-1100", light: "border-orange-100" },
  { dark: "border-yellow-100", light: "border-yellow-900" },
  { dark: "border-yellow-200", light: "border-yellow-800" },
  { dark: "border-yellow-300", light: "border-yellow-700" },
  { dark: "border-yellow-400", light: "border-yellow-600" },
  { dark: "border-yellow-500", light: "border-yellow-500" },
  { dark: "border-yellow-600", light: "border-yellow-400" },
  { dark: "border-yellow-700", light: "border-yellow-300" },
  { dark: "border-yellow-800", light: "border-yellow-200" },
  { dark: "border-yellow-900", light: "border-yellow-100" },
  { dark: "border-green-100", light: "border-green-900" },
  { dark: "border-green-200", light: "border-green-800" },
  { dark: "border-green-300", light: "border-green-700" },
  { dark: "border-green-400", light: "border-green-600" },
  { dark: "border-green-500", light: "border-green-500" },
  { dark: "border-green-600", light: "border-green-400" },
  { dark: "border-green-700", light: "border-green-300" },
  { dark: "border-green-800", light: "border-green-200" },
  { dark: "border-green-900", light: "border-green-100" },
  { dark: "border-blue-100", light: "border-blue-900" },
  { dark: "border-blue-200", light: "border-blue-800" },
  { dark: "border-blue-300", light: "border-blue-700" },
  { dark: "border-blue-400", light: "border-blue-600" },
  { dark: "border-blue-500", light: "border-blue-500" },
  { dark: "border-blue-600", light: "border-blue-400" },
  { dark: "border-blue-700", light: "border-blue-300" },
  { dark: "border-blue-800", light: "border-blue-200" },
  { dark: "border-blue-900", light: "border-blue-100" },
  { dark: "border-violet-100", light: "border-violet-900" },
  { dark: "border-violet-200", light: "border-violet-800" },
  { dark: "border-violet-300", light: "border-violet-700" },
  { dark: "border-violet-400", light: "border-violet-600" },
  { dark: "border-violet-500", light: "border-violet-500" },
  { dark: "border-violet-600", light: "border-violet-400" },
  { dark: "border-violet-700", light: "border-violet-300" },
  { dark: "border-violet-800", light: "border-violet-200" },
  { dark: "border-violet-900", light: "border-violet-100" },
  { dark: "border-pink-100", light: "border-pink-900" },
  { dark: "border-pink-200", light: "border-pink-800" },
  { dark: "border-pink-300", light: "border-pink-700" },
  { dark: "border-pink-400", light: "border-pink-600" },
  { dark: "border-pink-500", light: "border-pink-500" },
  { dark: "border-pink-600", light: "border-pink-400" },
  { dark: "border-pink-700", light: "border-pink-300" },
  { dark: "border-pink-800", light: "border-pink-200" },
  { dark: "border-pink-900", light: "border-pink-100" },
];

const colorMappings = [
  ...textColorMappings,
  ...bgColorMappings,
  ...additionalColorMappings,
];

export const convertTailwindClassToVar = (className: string) =>
  className.replace(/(text|bg|from|to)-([a-z0-9-]+)/gi, "var(--color-$2)");

export const determineThemeColor = (
  baseTheme: Theme,
  currentTheme: Theme,
  color: ColorClass,
) =>
  baseTheme === currentTheme
    ? color
    : colorMappings.find((set) => set[baseTheme] === color)?.[currentTheme] ||
      color;
