name: Remove old package versions
on:
  schedule:
    # every Monday 9:00am
    - cron: "*/5 * * * *"

jobs:
  remove-package-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Remove package versions
        uses: smartsquaregmbh/delete-old-packages@v0.2.0
        with:
          # See https://github.com/marketplace/actions/delete-old-packages for options
          names: ably-ui
          # should match 2.1.2.dev.3gdf4 and 2.1.2-dev.3gdf4
          version-pattern: "^\\d+\\.\\d+\\.\\d+(\\.|-)dev\\..+"
          keep: 20
