name: Lint and test

on:
  push:
    branches-ignore:
      - "gh-pages"
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run-linters-and-tests:
    name: Run linters and tests
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Verify pnpm installation
        run: pnpm --version
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Install playwright
        run: pnpm exec playwright install --with-deps
      - name: Lint
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: src
          eslint_extensions: js,ts,tsx
          eslint_auto_fix: false
          prettier: true
          prettier_dir: src
          prettier_extensions: js,ts,tsx
          prettier_auto_fix: false
      - name: Run Storybook test-runner
        run: pnpm test
