name: Release Ably UI
on:
  release:
    types: [published]

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      packages: "write"
      contents: "write"
      pull-requests: "write"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: "14.15.4"
      - run: npm install -g yarn
      - name: Grant permissions to Scripts
        run: |
          chmod +x "release.sh"
          chmod +x "./scripts/update-dependents.sh"
      - name: Release latest Ably UI version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          RUBYGEMS_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"
        run: |
          git config --global user.email "github@action.code"
          git config --global user.name "Github Action"
          ./scripts/release.sh "${GITHUB_REF/refs\/tags\//}"
        shell: bash
      - name: Create PR on Voltaire and Website
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: "./scripts/update-dependents.sh"
        shell: bash
