name: Release Ably UI
# on: push
on:
  release:
    types: [published]

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      repository-projects: write
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          token: ${{ secrets.REGISTRY_TOKEN }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: "12.16.3"
      - run: npm install -g yarn
      - name: Grant permissions to Scripts
        run: |
          chmod +x "release.sh"
          chmod +x "./scripts/update-dependents.sh"
      - name: Release latest Ably UI version
        env:
          GITHUB_REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: '${{ secrets.REGISTRY_USERNAME }}:${{ secrets.REGISTRY_TOKEN }}'
        run: |
          git config --global user.email "github@action.code"
          git config --global user.name "Github Action"
          ./release.sh "${GITHUB_REF/refs\/tags\//}"
        shell: bash
      - name: Create PR on Voltaire and Website
        env:
          GITHUB_REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: '${{ secrets.REGISTRY_USERNAME }}:${{ secrets.REGISTRY_TOKEN }}'
        run: "./scripts/update-dependents.sh"
        shell: bash
