name: Release Ably UI
on: push
# on:
  # release:
    # types: [published]

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: "12.16.3"
      - run: npm install -g yarn
      - name: Grant permissions to Scripts
        run: |
          chmod +x "release.sh"
      #     chmod +x "./scripts/update-dependents.sh"
      - name: Release latest Ably UI version
        env:
          GITHUB_REGISTRY_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
        run: |
          ./release.sh "${ABLY_TEST}"
          # GITHUB_REF/refs\/tags\//
        shell: bash
      # - name: Create PR on Voltaire and Website
      #   run: "./scripts/update-dependents.sh"
      - run: npm uninstall yarn
