name: Release Ably UI
on:
  release:
    types: [published]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkout Script
        uses: actions/checkout@v2
      - name: Grant permissions to Scripts
        run: |
          chmod +x "release.sh"
          chmod +x "./scripts/update-dependents.sh"
        shell: bash
      - name: Release latest Ably UI version
        run: "./release.sh"
        shell: bash
      - name: Create PR on Voltaire and Website
        run: "./scripts/update-dependents.sh"
        shell: bash
