name: Release packages

on:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Release latest Ably UI version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.email "github@action.code"
          git config --global user.name "Github Action"
          ./scripts/release.sh "${GITHUB_REF/refs\/tags\//}"
        shell: bash
  deploy-storybook:
    name: Deploy Storybook to GH Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: pnpm install --frozen-lockfile && pnpm build-storybook
      - name: Upload
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: preview
      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
